version: "3.9"
    
services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db_data:/var/lib/mongodb
      - ./mongod.conf:/etc/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGO_DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: MONGO_DB_PASSWORD

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://MONGO_DB_USERNAME:MONGO_DB_PASSWORD@172.18.0.2:27017/
